version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - smartfinanceadvisor-net

  frontend:
    image: node:14
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    networks:
      - smartfinanceadvisor-net

networks:
  smartfinanceadvisor-net:
    driver: bridge
